# Generated by Django 4.2.2 on 2024-06-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_difference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingentry',
            name='direction',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accountingproof',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
